Passwords guide (WIP)
solid-adventure/trivial-docs pull request #12
Opened 2023-12-11 18:44 UTC by elmerv

Passwords guide will provide information in regards to creating/updating passwords via endpoints in trivial-api.

2023-12-14 19:10 UTC, vgkids requested changes
Coming along!

2023-12-14 19:10 UTC, vgkids commented on docs/guides/passwords.md
> +The creation and resetting of passwords is a process that interacts with many endpoints and frontend paths. This guide breaks down every single step.
"The creation and resetting of passwords interacts with several endpoints across trivial-ui and trivial-api, this guide provides the general flow. For actual implementations of the API calls, the repos themselves are the definitive source."

2023-12-14 19:10 UTC, vgkids commented on docs/guides/passwords.md
> +
Add a note here that matches the readme callout:

   44: By default, new user registration is disabled. Set the env var `ENABLE_REGISTRATION=TRUE` and restart the server to enable.
   45  
   46  To create a one-off user without enabling registration, visit [http://localhost:3000/register?enableFeatures=registration](http://localhost:3000/register?enableFeatures=registration)

2023-12-14 19:10 UTC, vgkids commented on docs/guides/passwords.md
> +  <img v-else height = "200px" width = "200" src = "../assets/Reset_Password_Flow_Light.svg" />
width should be 400 to match dark

2023-12-14 19:10 UTC, vgkids commented on docs/guides/passwords.md
> +const organization = await fetch('http://localhost:3000/auth', {
Let's remove all of these code snippets, starting with this one. Our goal with the doc is to show the points you have to hit, but recreating in detail isn't necessary, and prone to error.

2023-12-14 19:10 UTC, vgkids commented on docs/guides/passwords.md
> +Please note that the `redirect_url` in the example is set to http://localhost:4000/resetpassword. Changes to the `redirect_url` can be made [here](https://github.com/solid-adventure/trivial-ui/blob/e
Add "In a future release, this will be configurable via an environment variable. See https://github.com/solid-adventure/trivial-ui/issues/27"

2023-12-14 19:10 UTC, vgkids commented on docs/guides/passwords.md
> +## Accepting Invite
"Accepting Invitations"

2023-12-14 19:10 UTC, vgkids commented on docs/guides/passwords.md
> +::: code-group
Similar to password resets, let's describe the flow of API calls rather than list the call itself. I can create new graphics if helpful.

2023-12-14 19:51 UTC, elmerv commented on docs/guides/passwords.md
> +::: code-group
I can make the graphic on lucid chart. Just want to confirm the flow before I begin: /organizations/{org_id}/invitations/new (trivial-ui)-> POST /auth/invitation (trivial-api) -> email -> 
/acceptinvitation (trivial-ui) -> PUT /auth/invitation (trivial-api) -> /signin (trivial-ui)

2023-12-14 19:57 UTC, vgkids commented on docs/guides/passwords.md
> +::: code-group
Looks right. Sent you the lucid chart of the reset graphic to copy and use a base.

2023-12-14 20:54 UTC, vgkids commented on docs/guides/passwords.md
> +::: code-group
@elmerv Graphic is great overall, but take a look at the step numbers.

2023-12-14 20:57 UTC, vgkids commented on docs/guides/passwords.md
> +`Redirected to http://redirection_url/resetpassword?query_parameters`
redirection_url should be in brackets to show that it's variable. The same for query_paramers, maybe? I don't know what these would be. If you're looking at trivial-ui, it adds auth headers that are managed by trivial-core to pass an access-token, etc.

2023-12-15 16:59 UTC, vgkids requested changes

2023-12-15 16:59 UTC, vgkids commented on docs/guides/passwords.md
> +To create a one-off user without enabling registration, visit [http://localhost:3000/register](enableFeatures=registration)
the query parameters have been dropped; this won't work

2023-12-15 16:59 UTC, vgkids commented on docs/guides/passwords.md
> +## Invitations
Organization Invitations

2023-12-15 17:43 UTC, vgkids approved these changes

2023-12-15 17:43 UTC, merged