Updated App Tags Guide
solid-adventure/trivial-docs pull request #4
Opened 2023-09-28 19:25 UTC by juancarbajal98

**Before**
The existing guide for App Tags instructed users on how to create and delete app tags through the rails console.

**After**
The App Tags guide has been updated to reflect the [changes to the API](https://github.com/solid-adventure/trivial-api/pull/178) for tag support. Now following this guide, users will be able to manage tags through the API instead of a local rails console. 

The guide goes over example API calls as well as example responses from the API.

2023-09-28 19:37 UTC, vgkids requested changes
So good.

In addition to the comments, can you create show some examples on exactly how apps are filtered. Similar to what I did on these tests:
https://github.com/solid-adventure/trivial-api/pull/181/files

2023-09-28 19:37 UTC, vgkids commented on docs/guides/app-tags.md
>  ```json
Let's extend this example response to show the tags array, and that it includes the items in the `tagged_with` param.

2023-09-28 19:37 UTC, vgkids commented on docs/guides/app-tags.md
> +By including the `tagged_with` query parameter, we can filter the response from `apps/index` to only include apps with certain tags:
`apps/index` is confusing, because it look like a URL but isn't. Let's describe as simply `apps/`.

2023-09-28 22:56 UTC, juancarbajal98 commented
@vgkids I appreciate the feedback! I included more detailed API responses and in an effort to keep things detailed while concise added `code-group` instances that are working to visually separate requests from their responses. If you think splitting this into two screens isn't what we want let me know and I could drop all the responses below the requests like we had before.

2023-09-29 01:42 UTC, vgkids requested changes
Looks good, I like breaking it into the request/response tabs.

Can you swap life-like ids (e.g., `cxg564s7dg`) for obvious fakes like XXXXXXX or {id}? You and I know these are truncated/fake, but it could appear like a security violation to an outsider or bot.

2023-09-29 16:29 UTC, vgkids approved these changes

2023-09-29 16:30 UTC, merged